'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'
Namespace Dingus

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="ConvertedBookingServiceSoap", [Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class ConvertedBookingService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private GetBookingsOperationCompleted As System.Threading.SendOrPostCallback

        Private MarkBookingsAsReceivedOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = "http://services.dingus-services.com/hd/tazzy/convertedbookingservice.asmx"
        End Sub

        '''<remarks/>
        Public Event GetBookingsCompleted As GetBookingsCompletedEventHandler

        '''<remarks/>
        Public Event MarkBookingsAsReceivedCompleted As MarkBookingsAsReceivedCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService/GetBookings", RequestNamespace:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService", ResponseNamespace:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function GetBookings(ByVal Credentials As Credentials, ByVal CustomerCode As String, ByVal HotelCode As String, ByVal DateFrom As Date, ByVal DateTo As Date, ByVal Key As String, ByVal NotFullBooking As Boolean) As GetBookinsRS
            Dim results() As Object = Me.Invoke("GetBookings", New Object() {Credentials, CustomerCode, HotelCode, DateFrom, DateTo, Key, NotFullBooking})
            Return CType(results(0), GetBookinsRS)
        End Function

        '''<remarks/>
        Public Function BeginGetBookings(ByVal Credentials As Credentials, ByVal CustomerCode As String, ByVal HotelCode As String, ByVal DateFrom As Date, ByVal DateTo As Date, ByVal Key As String, ByVal NotFullBooking As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetBookings", New Object() {Credentials, CustomerCode, HotelCode, DateFrom, DateTo, Key, NotFullBooking}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndGetBookings(ByVal asyncResult As System.IAsyncResult) As GetBookinsRS
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), GetBookinsRS)
        End Function

        '''<remarks/>
        Public Overloads Sub GetBookingsAsync(ByVal Credentials As Credentials, ByVal CustomerCode As String, ByVal HotelCode As String, ByVal DateFrom As Date, ByVal DateTo As Date, ByVal Key As String, ByVal NotFullBooking As Boolean)
            Me.GetBookingsAsync(Credentials, CustomerCode, HotelCode, DateFrom, DateTo, Key, NotFullBooking, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub GetBookingsAsync(ByVal Credentials As Credentials, ByVal CustomerCode As String, ByVal HotelCode As String, ByVal DateFrom As Date, ByVal DateTo As Date, ByVal Key As String, ByVal NotFullBooking As Boolean, ByVal userState As Object)
            If (Me.GetBookingsOperationCompleted Is Nothing) Then
                Me.GetBookingsOperationCompleted = AddressOf Me.OnGetBookingsOperationCompleted
            End If
            Me.InvokeAsync("GetBookings", New Object() {Credentials, CustomerCode, HotelCode, DateFrom, DateTo, Key, NotFullBooking}, Me.GetBookingsOperationCompleted, userState)
        End Sub

        Private Sub OnGetBookingsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetBookingsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetBookingsCompleted(Me, New GetBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService/MarkBookingsAsRe" & _
            "ceived", RequestNamespace:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService", ResponseNamespace:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function MarkBookingsAsReceived(ByVal Credentials As Credentials, ByVal CustomerCode As String, ByVal HotelCode As String, ByVal LocalizerCol() As String, ByVal Key As String) As SyncroRS
            Dim results() As Object = Me.Invoke("MarkBookingsAsReceived", New Object() {Credentials, CustomerCode, HotelCode, LocalizerCol, Key})
            Return CType(results(0), SyncroRS)
        End Function

        '''<remarks/>
        Public Function BeginMarkBookingsAsReceived(ByVal Credentials As Credentials, ByVal CustomerCode As String, ByVal HotelCode As String, ByVal LocalizerCol() As String, ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("MarkBookingsAsReceived", New Object() {Credentials, CustomerCode, HotelCode, LocalizerCol, Key}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndMarkBookingsAsReceived(ByVal asyncResult As System.IAsyncResult) As SyncroRS
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), SyncroRS)
        End Function

        '''<remarks/>
        Public Overloads Sub MarkBookingsAsReceivedAsync(ByVal Credentials As Credentials, ByVal CustomerCode As String, ByVal HotelCode As String, ByVal LocalizerCol() As String, ByVal Key As String)
            Me.MarkBookingsAsReceivedAsync(Credentials, CustomerCode, HotelCode, LocalizerCol, Key, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub MarkBookingsAsReceivedAsync(ByVal Credentials As Credentials, ByVal CustomerCode As String, ByVal HotelCode As String, ByVal LocalizerCol() As String, ByVal Key As String, ByVal userState As Object)
            If (Me.MarkBookingsAsReceivedOperationCompleted Is Nothing) Then
                Me.MarkBookingsAsReceivedOperationCompleted = AddressOf Me.OnMarkBookingsAsReceivedOperationCompleted
            End If
            Me.InvokeAsync("MarkBookingsAsReceived", New Object() {Credentials, CustomerCode, HotelCode, LocalizerCol, Key}, Me.MarkBookingsAsReceivedOperationCompleted, userState)
        End Sub

        Private Sub OnMarkBookingsAsReceivedOperationCompleted(ByVal arg As Object)
            If (Not (Me.MarkBookingsAsReceivedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent MarkBookingsAsReceivedCompleted(Me, New MarkBookingsAsReceivedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class Credentials

        Private languajeField As String

        Private passwordField As String

        Private userNameField As String

        '''<remarks/>
        Public Property Languaje() As String
            Get
                Return Me.languajeField
            End Get
            Set(ByVal value As String)
                Me.languajeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set(ByVal value As String)
                Me.passwordField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set(ByVal value As String)
                Me.userNameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class SyncroRS

        Private errorListField() As String

        Private successField As Boolean

        '''<remarks/>
        Public Property ErrorList() As String()
            Get
                Return Me.errorListField
            End Get
            Set(ByVal value As String())
                Me.errorListField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set(ByVal value As Boolean)
                Me.successField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class CancellationInfo

        Private roomNoField As Integer

        Private cancellationFeeField As Decimal

        Private cancellationLimitField As Date

        Private cancellationTextField As String

        Private noRefundableField As Boolean

        Private modifyCancellationFeeField As Boolean

        Private importModifyCancellationFeeField As Decimal

        '''<remarks/>
        Public Property RoomNo() As Integer
            Get
                Return Me.roomNoField
            End Get
            Set(ByVal value As Integer)
                Me.roomNoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CancellationFee() As Decimal
            Get
                Return Me.cancellationFeeField
            End Get
            Set(ByVal value As Decimal)
                Me.cancellationFeeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CancellationLimit() As Date
            Get
                Return Me.cancellationLimitField
            End Get
            Set(ByVal value As Date)
                Me.cancellationLimitField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CancellationText() As String
            Get
                Return Me.cancellationTextField
            End Get
            Set(ByVal value As String)
                Me.cancellationTextField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NoRefundable() As Boolean
            Get
                Return Me.noRefundableField
            End Get
            Set(ByVal value As Boolean)
                Me.noRefundableField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ModifyCancellationFee() As Boolean
            Get
                Return Me.modifyCancellationFeeField
            End Get
            Set(ByVal value As Boolean)
                Me.modifyCancellationFeeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ImportModifyCancellationFee() As Decimal
            Get
                Return Me.importModifyCancellationFeeField
            End Get
            Set(ByVal value As Decimal)
                Me.importModifyCancellationFeeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class Price

        Private rateIDField As Integer

        Private rateLineIDField As Integer

        Private amountField As Decimal

        Private codeField As String

        Private dayField As Date

        Private paxNoField As Integer

        Private roomNoField As Integer

        Private paxTypeField As PaxType

        Private priceLineTypeField As PriceLineType

        Private priceTypeField As PriceType

        Private suplTypeField As PriceSuplType

        Private roomPriceField As Boolean

        Private rateCodeField As String

        Private guaranteedField As Boolean

        '''<remarks/>
        Public Property RateID() As Integer
            Get
                Return Me.rateIDField
            End Get
            Set(ByVal value As Integer)
                Me.rateIDField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RateLineID() As Integer
            Get
                Return Me.rateLineIDField
            End Get
            Set(ByVal value As Integer)
                Me.rateLineIDField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set(ByVal value As Decimal)
                Me.amountField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set(ByVal value As String)
                Me.codeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Day() As Date
            Get
                Return Me.dayField
            End Get
            Set(ByVal value As Date)
                Me.dayField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaxNo() As Integer
            Get
                Return Me.paxNoField
            End Get
            Set(ByVal value As Integer)
                Me.paxNoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RoomNo() As Integer
            Get
                Return Me.roomNoField
            End Get
            Set(ByVal value As Integer)
                Me.roomNoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaxType() As PaxType
            Get
                Return Me.paxTypeField
            End Get
            Set(ByVal value As PaxType)
                Me.paxTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PriceLineType() As PriceLineType
            Get
                Return Me.priceLineTypeField
            End Get
            Set(ByVal value As PriceLineType)
                Me.priceLineTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PriceType() As PriceType
            Get
                Return Me.priceTypeField
            End Get
            Set(ByVal value As PriceType)
                Me.priceTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SuplType() As PriceSuplType
            Get
                Return Me.suplTypeField
            End Get
            Set(ByVal value As PriceSuplType)
                Me.suplTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RoomPrice() As Boolean
            Get
                Return Me.roomPriceField
            End Get
            Set(ByVal value As Boolean)
                Me.roomPriceField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RateCode() As String
            Get
                Return Me.rateCodeField
            End Get
            Set(ByVal value As String)
                Me.rateCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Guaranteed() As Boolean
            Get
                Return Me.guaranteedField
            End Get
            Set(ByVal value As Boolean)
                Me.guaranteedField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Public Enum PaxType

        '''<remarks/>
        ADT

        '''<remarks/>
        CHD

        '''<remarks/>
        ENF
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Public Enum PriceLineType

        '''<remarks/>
        Income

        '''<remarks/>
        Cost
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Public Enum PriceType

        '''<remarks/>
        Room

        '''<remarks/>
        Board

        '''<remarks/>
        Extra

        '''<remarks/>
        Supl

        '''<remarks/>
        [Nothing]

        '''<remarks/>
        CancellationFee

        '''<remarks/>
        Modify

        '''<remarks/>
        CashDiscount
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Public Enum PriceSuplType

        '''<remarks/>
        Supl

        '''<remarks/>
        Offer

        '''<remarks/>
        AxB

        '''<remarks/>
        Null
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class Pax

        Private paxAgeField As Integer

        Private paxNameField As String

        Private paxTypeField As PaxType

        Private paxTypeCodeField As String

        '''<remarks/>
        Public Property PaxAge() As Integer
            Get
                Return Me.paxAgeField
            End Get
            Set(ByVal value As Integer)
                Me.paxAgeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaxName() As String
            Get
                Return Me.paxNameField
            End Get
            Set(ByVal value As String)
                Me.paxNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaxType() As PaxType
            Get
                Return Me.paxTypeField
            End Get
            Set(ByVal value As PaxType)
                Me.paxTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaxTypeCode() As String
            Get
                Return Me.paxTypeCodeField
            End Get
            Set(ByVal value As String)
                Me.paxTypeCodeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class ComissionRS

        Private comissionTypeField As RateType

        Private percentField As Decimal

        Private comissionAmountField As Decimal

        Private netPriceField As Decimal

        Private miniumPriceField As Decimal

        '''<remarks/>
        Public Property ComissionType() As RateType
            Get
                Return Me.comissionTypeField
            End Get
            Set(ByVal value As RateType)
                Me.comissionTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Percent() As Decimal
            Get
                Return Me.percentField
            End Get
            Set(ByVal value As Decimal)
                Me.percentField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ComissionAmount() As Decimal
            Get
                Return Me.comissionAmountField
            End Get
            Set(ByVal value As Decimal)
                Me.comissionAmountField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NetPrice() As Decimal
            Get
                Return Me.netPriceField
            End Get
            Set(ByVal value As Decimal)
                Me.netPriceField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property MiniumPrice() As Decimal
            Get
                Return Me.miniumPriceField
            End Get
            Set(ByVal value As Decimal)
                Me.miniumPriceField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Public Enum RateType

        '''<remarks/>
        CP

        '''<remarks/>
        RRP
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class Stay

        Private roomNoField As Integer

        Private roomCodeField As String

        Private salesRoomCodeField As String

        Private discountAllotmentField As Boolean

        Private dateField As Date

        '''<remarks/>
        Public Property RoomNo() As Integer
            Get
                Return Me.roomNoField
            End Get
            Set(ByVal value As Integer)
                Me.roomNoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RoomCode() As String
            Get
                Return Me.roomCodeField
            End Get
            Set(ByVal value As String)
                Me.roomCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SalesRoomCode() As String
            Get
                Return Me.salesRoomCodeField
            End Get
            Set(ByVal value As String)
                Me.salesRoomCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DiscountAllotment() As Boolean
            Get
                Return Me.discountAllotmentField
            End Get
            Set(ByVal value As Boolean)
                Me.discountAllotmentField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set(ByVal value As Date)
                Me.dateField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class Charge

        Private chargeIDField As Integer

        Private chargeDateField As Date

        Private chargeAmountField As Decimal

        Private chargePaidField As Boolean

        Private roomNoField As Integer

        '''<remarks/>
        Public Property ChargeID() As Integer
            Get
                Return Me.chargeIDField
            End Get
            Set(ByVal value As Integer)
                Me.chargeIDField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ChargeDate() As Date
            Get
                Return Me.chargeDateField
            End Get
            Set(ByVal value As Date)
                Me.chargeDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ChargeAmount() As Decimal
            Get
                Return Me.chargeAmountField
            End Get
            Set(ByVal value As Decimal)
                Me.chargeAmountField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ChargePaid() As Boolean
            Get
                Return Me.chargePaidField
            End Get
            Set(ByVal value As Boolean)
                Me.chargePaidField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RoomNo() As Integer
            Get
                Return Me.roomNoField
            End Get
            Set(ByVal value As Integer)
                Me.roomNoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class Payment

        Private paymentIDField As Integer

        Private paymentDateField As Date

        Private paymentAmountField As Decimal

        Private paymentCurrencyField As String

        Private paymentConfirmationField As String

        Private paymentFormField As String

        '''<remarks/>
        Public Property PaymentID() As Integer
            Get
                Return Me.paymentIDField
            End Get
            Set(ByVal value As Integer)
                Me.paymentIDField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaymentDate() As Date
            Get
                Return Me.paymentDateField
            End Get
            Set(ByVal value As Date)
                Me.paymentDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaymentAmount() As Decimal
            Get
                Return Me.paymentAmountField
            End Get
            Set(ByVal value As Decimal)
                Me.paymentAmountField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaymentCurrency() As String
            Get
                Return Me.paymentCurrencyField
            End Get
            Set(ByVal value As String)
                Me.paymentCurrencyField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaymentConfirmation() As String
            Get
                Return Me.paymentConfirmationField
            End Get
            Set(ByVal value As String)
                Me.paymentConfirmationField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PaymentForm() As String
            Get
                Return Me.paymentFormField
            End Get
            Set(ByVal value As String)
                Me.paymentFormField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class Data

        Private codeField As String

        Private valueField As String

        Private isEncField As Boolean

        Private encBookingDataField As Boolean

        Private encTypeField As TipoEncriptacion

        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set(ByVal value As String)
                Me.codeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(ByVal value As String)
                Me.valueField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IsEnc() As Boolean
            Get
                Return Me.isEncField
            End Get
            Set(ByVal value As Boolean)
                Me.isEncField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EncBookingData() As Boolean
            Get
                Return Me.encBookingDataField
            End Get
            Set(ByVal value As Boolean)
                Me.encBookingDataField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EncType() As TipoEncriptacion
            Get
                Return Me.encTypeField
            End Get
            Set(ByVal value As TipoEncriptacion)
                Me.encTypeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Public Enum TipoEncriptacion

        '''<remarks/>
        Rijndael

        '''<remarks/>
        RC2

        '''<remarks/>
        DES

        '''<remarks/>
        TripleDES
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class Extra

        Private dateFromField As Date

        Private dateToField As Date

        Private extraCodeField As String

        Private extraNameField As String

        Private extraQuantityField As Integer

        Private noPaxField As Integer

        Private promotionCodeField As String

        '''<remarks/>
        Public Property DateFrom() As Date
            Get
                Return Me.dateFromField
            End Get
            Set(ByVal value As Date)
                Me.dateFromField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DateTo() As Date
            Get
                Return Me.dateToField
            End Get
            Set(ByVal value As Date)
                Me.dateToField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ExtraCode() As String
            Get
                Return Me.extraCodeField
            End Get
            Set(ByVal value As String)
                Me.extraCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ExtraName() As String
            Get
                Return Me.extraNameField
            End Get
            Set(ByVal value As String)
                Me.extraNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ExtraQuantity() As Integer
            Get
                Return Me.extraQuantityField
            End Get
            Set(ByVal value As Integer)
                Me.extraQuantityField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NoPax() As Integer
            Get
                Return Me.noPaxField
            End Get
            Set(ByVal value As Integer)
                Me.noPaxField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PromotionCode() As String
            Get
                Return Me.promotionCodeField
            End Get
            Set(ByVal value As String)
                Me.promotionCodeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class [Error]

        Private errorCodeField As String

        Private errorTextField As String

        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set(ByVal value As String)
                Me.errorCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorText() As String
            Get
                Return Me.errorTextField
            End Get
            Set(ByVal value As String)
                Me.errorTextField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class Criterion

        Private criterionIdField As Integer

        Private criterionDescriptionField As String

        Private criterionTypeField As String

        Private criterionValueField As String

        '''<remarks/>
        Public Property CriterionId() As Integer
            Get
                Return Me.criterionIdField
            End Get
            Set(ByVal value As Integer)
                Me.criterionIdField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CriterionDescription() As String
            Get
                Return Me.criterionDescriptionField
            End Get
            Set(ByVal value As String)
                Me.criterionDescriptionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CriterionType() As String
            Get
                Return Me.criterionTypeField
            End Get
            Set(ByVal value As String)
                Me.criterionTypeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CriterionValue() As String
            Get
                Return Me.criterionValueField
            End Get
            Set(ByVal value As String)
                Me.criterionValueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class BookingRS

        Private sequenceIDField As Integer

        Private allotmentBlockCodeField As String

        Private statusField As StatusBookingRS

        Private rqField As Boolean

        Private boardCodeField As String

        Private boardNameField As String

        Private chainCodeField As String

        Private chainNameField As String

        Private criteriaField() As Criterion

        Private customerCodeField As String

        Private customerNameField As String

        Private dateFromField As Date

        Private dateToField As Date

        Private dateSaleField As Date

        Private errorField As Boolean

        Private errorsField() As [Error]

        Private extrasField() As Extra

        Private bookingDataField() As Data

        Private paymentsField() As Payment

        Private chargesField() As Charge

        Private staysField() As Stay

        Private comissionInfoField As ComissionRS

        Private hotelCodeField As String

        Private hotelNameField As String

        Private localizerField As String

        Private sendField As Boolean

        Private sendPMSField As Boolean

        Private errorPMSField As Boolean

        Private errorPMSTextField As String

        Private offerAppliedField As Boolean

        Private bookingOutOfAllotmentField As Boolean

        Private paxesField() As Pax

        Private priceDetailsField() As Price

        Private contractPriceDetailsField() As Price

        Private resRefField As String

        Private roomCodeField As String

        Private roomNameField As String

        Private totalPriceField As Decimal

        Private vendorCodeField As String

        Private vendorNameField As String

        Private salesRoomCodeField As String

        Private roomReferenceField As String

        Private currencyCodeField As String

        Private customerAllotmentGroupField As String

        Private customerRateGroupField As String

        Private promotionCodeField As String

        Private promotionDescriptionField As String

        Private bookingInCheckOutField As Boolean

        Private pMSCodeField As String

        Private insertUserField As String

        Private inserDateTimeField As Date

        Private modifyUserField As String

        Private modifyDateTimeField As Date

        Private cancellationInfoCollectionField() As CancellationInfo

        '''<remarks/>
        Public Property SequenceID() As Integer
            Get
                Return Me.sequenceIDField
            End Get
            Set(ByVal value As Integer)
                Me.sequenceIDField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AllotmentBlockCode() As String
            Get
                Return Me.allotmentBlockCodeField
            End Get
            Set(ByVal value As String)
                Me.allotmentBlockCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Status() As StatusBookingRS
            Get
                Return Me.statusField
            End Get
            Set(ByVal value As StatusBookingRS)
                Me.statusField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RQ() As Boolean
            Get
                Return Me.rqField
            End Get
            Set(ByVal value As Boolean)
                Me.rqField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property BoardCode() As String
            Get
                Return Me.boardCodeField
            End Get
            Set(ByVal value As String)
                Me.boardCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property BoardName() As String
            Get
                Return Me.boardNameField
            End Get
            Set(ByVal value As String)
                Me.boardNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ChainCode() As String
            Get
                Return Me.chainCodeField
            End Get
            Set(ByVal value As String)
                Me.chainCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ChainName() As String
            Get
                Return Me.chainNameField
            End Get
            Set(ByVal value As String)
                Me.chainNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Criteria() As Criterion()
            Get
                Return Me.criteriaField
            End Get
            Set(ByVal value As Criterion())
                Me.criteriaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CustomerCode() As String
            Get
                Return Me.customerCodeField
            End Get
            Set(ByVal value As String)
                Me.customerCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CustomerName() As String
            Get
                Return Me.customerNameField
            End Get
            Set(ByVal value As String)
                Me.customerNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DateFrom() As Date
            Get
                Return Me.dateFromField
            End Get
            Set(ByVal value As Date)
                Me.dateFromField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DateTo() As Date
            Get
                Return Me.dateToField
            End Get
            Set(ByVal value As Date)
                Me.dateToField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DateSale() As Date
            Get
                Return Me.dateSaleField
            End Get
            Set(ByVal value As Date)
                Me.dateSaleField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property [Error]() As Boolean
            Get
                Return Me.errorField
            End Get
            Set(ByVal value As Boolean)
                Me.errorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Errors() As [Error]()
            Get
                Return Me.errorsField
            End Get
            Set(ByVal value As [Error]())
                Me.errorsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Extras() As Extra()
            Get
                Return Me.extrasField
            End Get
            Set(ByVal value As Extra())
                Me.extrasField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property BookingData() As Data()
            Get
                Return Me.bookingDataField
            End Get
            Set(ByVal value As Data())
                Me.bookingDataField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Payments() As Payment()
            Get
                Return Me.paymentsField
            End Get
            Set(ByVal value As Payment())
                Me.paymentsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Charges() As Charge()
            Get
                Return Me.chargesField
            End Get
            Set(ByVal value As Charge())
                Me.chargesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Stays() As Stay()
            Get
                Return Me.staysField
            End Get
            Set(ByVal value As Stay())
                Me.staysField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ComissionInfo() As ComissionRS
            Get
                Return Me.comissionInfoField
            End Get
            Set(ByVal value As ComissionRS)
                Me.comissionInfoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property HotelCode() As String
            Get
                Return Me.hotelCodeField
            End Get
            Set(ByVal value As String)
                Me.hotelCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property HotelName() As String
            Get
                Return Me.hotelNameField
            End Get
            Set(ByVal value As String)
                Me.hotelNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Localizer() As String
            Get
                Return Me.localizerField
            End Get
            Set(ByVal value As String)
                Me.localizerField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Send() As Boolean
            Get
                Return Me.sendField
            End Get
            Set(ByVal value As Boolean)
                Me.sendField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SendPMS() As Boolean
            Get
                Return Me.sendPMSField
            End Get
            Set(ByVal value As Boolean)
                Me.sendPMSField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorPMS() As Boolean
            Get
                Return Me.errorPMSField
            End Get
            Set(ByVal value As Boolean)
                Me.errorPMSField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorPMSText() As String
            Get
                Return Me.errorPMSTextField
            End Get
            Set(ByVal value As String)
                Me.errorPMSTextField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OfferApplied() As Boolean
            Get
                Return Me.offerAppliedField
            End Get
            Set(ByVal value As Boolean)
                Me.offerAppliedField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property BookingOutOfAllotment() As Boolean
            Get
                Return Me.bookingOutOfAllotmentField
            End Get
            Set(ByVal value As Boolean)
                Me.bookingOutOfAllotmentField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Paxes() As Pax()
            Get
                Return Me.paxesField
            End Get
            Set(ByVal value As Pax())
                Me.paxesField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PriceDetails() As Price()
            Get
                Return Me.priceDetailsField
            End Get
            Set(ByVal value As Price())
                Me.priceDetailsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ContractPriceDetails() As Price()
            Get
                Return Me.contractPriceDetailsField
            End Get
            Set(ByVal value As Price())
                Me.contractPriceDetailsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ResRef() As String
            Get
                Return Me.resRefField
            End Get
            Set(ByVal value As String)
                Me.resRefField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RoomCode() As String
            Get
                Return Me.roomCodeField
            End Get
            Set(ByVal value As String)
                Me.roomCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RoomName() As String
            Get
                Return Me.roomNameField
            End Get
            Set(ByVal value As String)
                Me.roomNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalPrice() As Decimal
            Get
                Return Me.totalPriceField
            End Get
            Set(ByVal value As Decimal)
                Me.totalPriceField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorCode() As String
            Get
                Return Me.vendorCodeField
            End Get
            Set(ByVal value As String)
                Me.vendorCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VendorName() As String
            Get
                Return Me.vendorNameField
            End Get
            Set(ByVal value As String)
                Me.vendorNameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SalesRoomCode() As String
            Get
                Return Me.salesRoomCodeField
            End Get
            Set(ByVal value As String)
                Me.salesRoomCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RoomReference() As String
            Get
                Return Me.roomReferenceField
            End Get
            Set(ByVal value As String)
                Me.roomReferenceField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CurrencyCode() As String
            Get
                Return Me.currencyCodeField
            End Get
            Set(ByVal value As String)
                Me.currencyCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CustomerAllotmentGroup() As String
            Get
                Return Me.customerAllotmentGroupField
            End Get
            Set(ByVal value As String)
                Me.customerAllotmentGroupField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CustomerRateGroup() As String
            Get
                Return Me.customerRateGroupField
            End Get
            Set(ByVal value As String)
                Me.customerRateGroupField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PromotionCode() As String
            Get
                Return Me.promotionCodeField
            End Get
            Set(ByVal value As String)
                Me.promotionCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PromotionDescription() As String
            Get
                Return Me.promotionDescriptionField
            End Get
            Set(ByVal value As String)
                Me.promotionDescriptionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property BookingInCheckOut() As Boolean
            Get
                Return Me.bookingInCheckOutField
            End Get
            Set(ByVal value As Boolean)
                Me.bookingInCheckOutField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PMSCode() As String
            Get
                Return Me.pMSCodeField
            End Get
            Set(ByVal value As String)
                Me.pMSCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InsertUser() As String
            Get
                Return Me.insertUserField
            End Get
            Set(ByVal value As String)
                Me.insertUserField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InserDateTime() As Date
            Get
                Return Me.inserDateTimeField
            End Get
            Set(ByVal value As Date)
                Me.inserDateTimeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ModifyUser() As String
            Get
                Return Me.modifyUserField
            End Get
            Set(ByVal value As String)
                Me.modifyUserField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ModifyDateTime() As Date
            Get
                Return Me.modifyDateTimeField
            End Get
            Set(ByVal value As Date)
                Me.modifyDateTimeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CancellationInfoCollection() As CancellationInfo()
            Get
                Return Me.cancellationInfoCollectionField
            End Get
            Set(ByVal value As CancellationInfo())
                Me.cancellationInfoCollectionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Public Enum StatusBookingRS

        '''<remarks/>
        [New]

        '''<remarks/>
        Modify

        '''<remarks/>
        Cancel

        '''<remarks/>
        Rejected

        '''<remarks/>
        Waiting
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://orca.orangetech.es/Tazzyv30/Tazzy/ConverterBookingService")> _
    Partial Public Class GetBookinsRS

        Private bookinsField() As BookingRS

        Private confirmCodeField As String

        Private errorListField() As String

        Private successField As Boolean

        '''<remarks/>
        Public Property Bookins() As BookingRS()
            Get
                Return Me.bookinsField
            End Get
            Set(ByVal value As BookingRS())
                Me.bookinsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ConfirmCode() As String
            Get
                Return Me.confirmCodeField
            End Get
            Set(ByVal value As String)
                Me.confirmCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ErrorList() As String()
            Get
                Return Me.errorListField
            End Get
            Set(ByVal value As String())
                Me.errorListField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set(ByVal value As Boolean)
                Me.successField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub GetBookingsCompletedEventHandler(ByVal sender As Object, ByVal e As GetBookingsCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class GetBookingsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As GetBookinsRS
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), GetBookinsRS)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub MarkBookingsAsReceivedCompletedEventHandler(ByVal sender As Object, ByVal e As MarkBookingsAsReceivedCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class MarkBookingsAsReceivedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As SyncroRS
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), SyncroRS)
            End Get
        End Property
    End Class
End Namespace
