
namespace Geshotel.Contratos {
    export interface ClientesRow {
        ClienteId?: number;
        Razon?: string;
        DescCorta?: string;
        EmpresaId?: number;
        AgenciaId?: number;
        ClienteDefecto?: boolean;
        GrupoClienteId?: number;
        TipoDocumentoId?: string;
        Nif?: string;
        FechaDocumento?: string;
        Direccion?: string;
        Poblacion?: string;
        Zip?: string;
        NacionId?: number;
        ProvinciaId?: number;
        CtaContableAnticipo?: string;
        CtaContable?: string;
        DptoContable?: string;
        CtaDepositos?: string;
        Telefono?: string;
        Email?: string;
        Fax?: string;
        Contacto?: string;
        TelefonoContacto?: string;
        FaxContacto?: string;
        EmailContacto?: string;
        CifFra?: string;
        DireccionFra?: string;
        PoblacionFra?: string;
        ZipFra?: string;
        NacionIdFactura?: number;
        ProvinciaIdFactura?: number;
        ClienteFactura?: boolean;
        ClienteHuesped?: boolean;
        PermiteCredito?: boolean;
        LimiteCredito?: number;
        FacturaAnticipada?: boolean;
        VencimientoFacturasId?: number;
        UserId?: number;
        FechaModificacion?: string;
        ClienteBavel?: string;
        DingusExtras?: boolean;
        Empresa?: string;
        EmpresaEmpresaContable?: string;
        EmpresaDireccion?: string;
        EmpresaPoblacion?: string;
        EmpresaZip?: string;
        EmpresaProvinciaId?: number;
        EmpresaTelefono?: string;
        EmpresaFax?: string;
        EmpresaCif?: string;
        EmpresaRutaFicheros?: string;
        AgenciaRazon?: string;
        Nacion?: string;
        Provincia?: string;
        NacionIdFacturaNacion?: string;
    }

    export namespace ClientesRow {
        export const idProperty = 'ClienteId';
        export const nameProperty = 'Razon';
        export const localTextPrefix = 'Contratos.Clientes';

        export namespace Fields {
            export declare const ClienteId;
            export declare const Razon;
            export declare const DescCorta;
            export declare const EmpresaId;
            export declare const AgenciaId;
            export declare const ClienteDefecto;
            export declare const GrupoClienteId;
            export declare const TipoDocumentoId;
            export declare const Nif;
            export declare const FechaDocumento;
            export declare const Direccion;
            export declare const Poblacion;
            export declare const Zip;
            export declare const NacionId;
            export declare const ProvinciaId;
            export declare const CtaContableAnticipo;
            export declare const CtaContable;
            export declare const DptoContable;
            export declare const CtaDepositos;
            export declare const Telefono;
            export declare const Email;
            export declare const Fax;
            export declare const Contacto;
            export declare const TelefonoContacto;
            export declare const FaxContacto;
            export declare const EmailContacto;
            export declare const CifFra;
            export declare const DireccionFra;
            export declare const PoblacionFra;
            export declare const ZipFra;
            export declare const NacionIdFactura;
            export declare const ProvinciaIdFactura;
            export declare const ClienteFactura;
            export declare const ClienteHuesped;
            export declare const PermiteCredito;
            export declare const LimiteCredito;
            export declare const FacturaAnticipada;
            export declare const VencimientoFacturasId;
            export declare const UserId;
            export declare const FechaModificacion;
            export declare const ClienteBavel;
            export declare const DingusExtras;
            export declare const Empresa: string;
            export declare const EmpresaEmpresaContable: string;
            export declare const EmpresaDireccion: string;
            export declare const EmpresaPoblacion: string;
            export declare const EmpresaZip: string;
            export declare const EmpresaProvinciaId: string;
            export declare const EmpresaTelefono: string;
            export declare const EmpresaFax: string;
            export declare const EmpresaCif: string;
            export declare const EmpresaRutaFicheros: string;
            export declare const AgenciaRazon: string;
            export declare const AgenciaDescCorta: string;
            export declare const AgenciaEmpresaId: string;
            export declare const AgenciaAgenciaId: string;
            export declare const AgenciaClienteDefecto: string;
            export declare const AgenciaGrupoClienteId: string;
            export declare const AgenciaTipoDocumentoId: string;
            export declare const AgenciaNif: string;
            export declare const AgenciaFechaDocumento: string;
            export declare const AgenciaDireccion: string;
            export declare const AgenciaPoblacion: string;
            export declare const AgenciaZip: string;
            export declare const AgenciaNacionId: string;
            export declare const AgenciaProvinciaId: string;
            export declare const AgenciaCtaContableAnticipo: string;
            export declare const AgenciaCtaContable: string;
            export declare const AgenciaDptoContable: string;
            export declare const AgenciaCtaDepositos: string;
            export declare const AgenciaTelefono: string;
            export declare const AgenciaEmail: string;
            export declare const AgenciaFax: string;
            export declare const AgenciaContacto: string;
            export declare const AgenciaTelefonoContacto: string;
            export declare const AgenciaFaxContacto: string;
            export declare const AgenciaEmailContacto: string;
            export declare const AgenciaCifFra: string;
            export declare const AgenciaDireccionFra: string;
            export declare const AgenciaPoblacionFra: string;
            export declare const AgenciaZipFra: string;
            export declare const AgenciaNacionIdFactura: string;
            export declare const AgenciaProvinciaIdFactura: string;
            export declare const AgenciaClienteFactura: string;
            export declare const AgenciaClienteHuesped: string;
            export declare const AgenciaPermiteCredito: string;
            export declare const AgenciaLimiteCredito: string;
            export declare const AgenciaFacturaAnticipada: string;
            export declare const AgenciaVencimientoFacturasId: string;
            export declare const AgenciaUserId: string;
            export declare const AgenciaFechaModificacion: string;
            export declare const AgenciaClienteBavel: string;
            export declare const AgenciaDingusExtras: string;
            export declare const Nacion: string;
            export declare const NacionDescCorta: string;
            export declare const NacionMonedaId: string;
            export declare const NacionIdiomaId: string;
            export declare const NacionNumeroIne: string;
            export declare const NacionPaisIsta: string;
            export declare const NacionDefecto: string;
            export declare const NacionNombreReal: string;
            export declare const NacionIdiomaMails: string;
            export declare const Provincia: string;
            export declare const ProvinciaComunidadAutonomaId: string;
            export declare const ProvinciaNacionId: string;
            export declare const ProvinciaProvinciaIsta: string;
            export declare const ProvinciaDefectoIsta: string;
            export declare const NacionIdFacturaNacion: string;
            export declare const NacionIdFacturaDescCorta: string;
            export declare const NacionIdFacturaMonedaId: string;
            export declare const NacionIdFacturaIdiomaId: string;
            export declare const NacionIdFacturaNumeroIne: string;
            export declare const NacionIdFacturaPaisIsta: string;
            export declare const NacionIdFacturaDefecto: string;
            export declare const NacionIdFacturaNombreReal: string;
            export declare const NacionIdFacturaIdiomaMails: string;
            export declare const ProvinciaIdFacturaProvincia: string;
            export declare const ProvinciaIdFacturaComunidadAutonomaId: string;
            export declare const ProvinciaIdFacturaNacionId: string;
            export declare const ProvinciaIdFacturaProvinciaIsta: string;
            export declare const ProvinciaIdFacturaDefectoIsta: string;
        }

        ['ClienteId', 'Razon', 'DescCorta', 'EmpresaId', 'AgenciaId', 'ClienteDefecto', 'GrupoClienteId', 'TipoDocumentoId', 'Nif', 'FechaDocumento', 'Direccion', 'Poblacion', 'Zip', 'NacionId', 'ProvinciaId', 'CtaContableAnticipo', 'CtaContable', 'DptoContable', 'CtaDepositos', 'Telefono', 'Email', 'Fax', 'Contacto', 'TelefonoContacto', 'FaxContacto', 'EmailContacto', 'CifFra', 'DireccionFra', 'PoblacionFra', 'ZipFra', 'NacionIdFactura', 'ProvinciaIdFactura', 'ClienteFactura', 'ClienteHuesped', 'PermiteCredito', 'LimiteCredito', 'FacturaAnticipada', 'VencimientoFacturasId', 'UserId', 'FechaModificacion', 'ClienteBavel', 'DingusExtras', 'Empresa', 'EmpresaEmpresaContable', 'EmpresaDireccion', 'EmpresaPoblacion', 'EmpresaZip', 'EmpresaProvinciaId', 'EmpresaTelefono', 'EmpresaFax', 'EmpresaCif', 'EmpresaRutaFicheros', 'AgenciaRazon', 'AgenciaDescCorta', 'AgenciaEmpresaId', 'AgenciaAgenciaId', 'AgenciaClienteDefecto', 'AgenciaGrupoClienteId', 'AgenciaTipoDocumentoId', 'AgenciaNif', 'AgenciaFechaDocumento', 'AgenciaDireccion', 'AgenciaPoblacion', 'AgenciaZip', 'AgenciaNacionId', 'AgenciaProvinciaId', 'AgenciaCtaContableAnticipo', 'AgenciaCtaContable', 'AgenciaDptoContable', 'AgenciaCtaDepositos', 'AgenciaTelefono', 'AgenciaEmail', 'AgenciaFax', 'AgenciaContacto', 'AgenciaTelefonoContacto', 'AgenciaFaxContacto', 'AgenciaEmailContacto', 'AgenciaCifFra', 'AgenciaDireccionFra', 'AgenciaPoblacionFra', 'AgenciaZipFra', 'AgenciaNacionIdFactura', 'AgenciaProvinciaIdFactura', 'AgenciaClienteFactura', 'AgenciaClienteHuesped', 'AgenciaPermiteCredito', 'AgenciaLimiteCredito', 'AgenciaFacturaAnticipada', 'AgenciaVencimientoFacturasId', 'AgenciaUserId', 'AgenciaFechaModificacion', 'AgenciaClienteBavel', 'AgenciaDingusExtras', 'Nacion', 'NacionDescCorta', 'NacionMonedaId', 'NacionIdiomaId', 'NacionNumeroIne', 'NacionPaisIsta', 'NacionDefecto', 'NacionNombreReal', 'NacionIdiomaMails', 'Provincia', 'ProvinciaComunidadAutonomaId', 'ProvinciaNacionId', 'ProvinciaProvinciaIsta', 'ProvinciaDefectoIsta', 'NacionIdFacturaNacion', 'NacionIdFacturaDescCorta', 'NacionIdFacturaMonedaId', 'NacionIdFacturaIdiomaId', 'NacionIdFacturaNumeroIne', 'NacionIdFacturaPaisIsta', 'NacionIdFacturaDefecto', 'NacionIdFacturaNombreReal', 'NacionIdFacturaIdiomaMails', 'ProvinciaIdFacturaProvincia', 'ProvinciaIdFacturaComunidadAutonomaId', 'ProvinciaIdFacturaNacionId', 'ProvinciaIdFacturaProvinciaIsta', 'ProvinciaIdFacturaDefectoIsta'].forEach(x => (<any>Fields)[x] = x);
    }
}

