
namespace Geshotel.Contratos {
    export interface HabitacionesRow {
        HabitacionId?: number;
        HotelId?: number;
        NumeroHabitacion?: string;
        TipoHabitacionId?: number;
        Extension?: number;
        Observaciones?: string;
        SituacionId?: number;
        FechaInicio?: string;
        EstadoTelefono?: number;
        EstadoProcesado?: number;
        HabitacionIsta?: string;
        ZonaLimpiezaId?: number;
        Lat?: number;
        Lng?: number;
        PrimaryImage?: string;
        Galleryimages?: string;
        Planta?: number;
        UserId?: number;
        FechaModificacion?: string;
        Hotel?: string;
        HotelEmpresaId?: number;
        HotelTipoHotelId?: number;
        HotelCategoriaId?: number;
        HotelNombreCorto?: string;
        HotelDireccion?: string;
        HotelPoblacion?: string;
        HotelZip?: string;
        HotelProvinciaId?: number;
        HotelNacionId?: number;
        HotelTelefono?: string;
        HotelFax?: string;
        HotelCtaManocorriente?: string;
        HotelDptoContable?: string;
        HotelCtaContableCajas?: string;
        HotelCtaContableBanco?: string;
        HotelFechaInicioPrograma?: string;
        HotelRutaFicheroPolicia?: string;
        HotelContadorFicheroPolicia?: number;
        HotelIdentificadorFicheroPolicia?: string;
        HotelEmailReservas?: string;
        HotelEmailVentas?: string;
        HotelEmailSmtp?: string;
        HotelTextoCancelacion?: string;
        HotelUsuarioIsta?: string;
        HotelPasswordIsta?: string;
        HotelUrlIsta?: string;
        HotelMunicipioIsta?: string;
        HotelNumeroRegistroIsta?: number;
        HotelRutaBavel?: string;
        HotelDingusUsuario?: string;
        HotelDingusPassword?: string;
        HotelDingusHotelCode?: string;
        HotelDingusTraductor?: string;
        HotelDingusUrl?: string;
        HotelCheckinOnLine?: number;
        HotelMinimoDiasCheckinOnline?: number;
        HotelZoomMapa?: number;
        HotelLat?: number;
        HotelLng?: number;
        HotelAncho?: number;
        HotelAlto?: number;
        HotelOverbookingLimit?: number;
        TipoHabitacionDescCorta?: string;
        TipoHabitacionDescripcion?: string;
        TipoHabitacionGrupoHabitacionId?: number;
        TipoHabitacionNumeroPersonas?: number;
        TipoHabitacionDesvios?: number;
        TipoHabitacionNoShow?: number;
        Situacion?: string;
        ZonaLimpiezaHotelId?: number;
        ZonaLimpiezaNombreZona?: string;
    }

    export namespace HabitacionesRow {
        export const idProperty = 'HabitacionId';
        export const nameProperty = 'NumeroHabitacion';
        export const localTextPrefix = 'Contratos.Habitaciones';

        export namespace Fields {
            export declare const HabitacionId;
            export declare const HotelId;
            export declare const NumeroHabitacion;
            export declare const TipoHabitacionId;
            export declare const Extension;
            export declare const Observaciones;
            export declare const SituacionId;
            export declare const FechaInicio;
            export declare const EstadoTelefono;
            export declare const EstadoProcesado;
            export declare const HabitacionIsta;
            export declare const ZonaLimpiezaId;
            export declare const Lat;
            export declare const Lng;
            export declare const PrimaryImage;
            export declare const Galleryimages;
            export declare const Planta;
            export declare const UserId;
            export declare const FechaModificacion;
            export declare const Hotel: string;
            export declare const HotelEmpresaId: string;
            export declare const HotelTipoHotelId: string;
            export declare const HotelCategoriaId: string;
            export declare const HotelNombreCorto: string;
            export declare const HotelDireccion: string;
            export declare const HotelPoblacion: string;
            export declare const HotelZip: string;
            export declare const HotelProvinciaId: string;
            export declare const HotelNacionId: string;
            export declare const HotelTelefono: string;
            export declare const HotelFax: string;
            export declare const HotelCtaManocorriente: string;
            export declare const HotelDptoContable: string;
            export declare const HotelCtaContableCajas: string;
            export declare const HotelCtaContableBanco: string;
            export declare const HotelFechaInicioPrograma: string;
            export declare const HotelRutaFicheroPolicia: string;
            export declare const HotelContadorFicheroPolicia: string;
            export declare const HotelIdentificadorFicheroPolicia: string;
            export declare const HotelEmailReservas: string;
            export declare const HotelEmailVentas: string;
            export declare const HotelEmailSmtp: string;
            export declare const HotelTextoCancelacion: string;
            export declare const HotelUsuarioIsta: string;
            export declare const HotelPasswordIsta: string;
            export declare const HotelUrlIsta: string;
            export declare const HotelMunicipioIsta: string;
            export declare const HotelNumeroRegistroIsta: string;
            export declare const HotelRutaBavel: string;
            export declare const HotelDingusUsuario: string;
            export declare const HotelDingusPassword: string;
            export declare const HotelDingusHotelCode: string;
            export declare const HotelDingusTraductor: string;
            export declare const HotelDingusUrl: string;
            export declare const HotelCheckinOnLine: string;
            export declare const HotelMinimoDiasCheckinOnline: string;
            export declare const HotelZoomMapa: string;
            export declare const HotelLat: string;
            export declare const HotelLng: string;
            export declare const HotelAncho: string;
            export declare const HotelAlto: string;
            export declare const HotelOverbookingLimit: string;
            export declare const TipoHabitacionDescCorta: string;
            export declare const TipoHabitacionDescripcion: string;
            export declare const TipoHabitacionGrupoHabitacionId: string;
            export declare const TipoHabitacionNumeroPersonas: string;
            export declare const TipoHabitacionDesvios: string;
            export declare const TipoHabitacionNoShow: string;
            export declare const Situacion: string;
            export declare const ZonaLimpiezaHotelId: string;
            export declare const ZonaLimpiezaNombreZona: string;
        }

        ['HabitacionId', 'HotelId', 'NumeroHabitacion', 'TipoHabitacionId', 'Extension', 'Observaciones', 'SituacionId', 'FechaInicio', 'EstadoTelefono', 'EstadoProcesado', 'HabitacionIsta', 'ZonaLimpiezaId', 'Lat', 'Lng', 'PrimaryImage', 'Galleryimages', 'Planta', 'UserId', 'FechaModificacion', 'Hotel', 'HotelEmpresaId', 'HotelTipoHotelId', 'HotelCategoriaId', 'HotelNombreCorto', 'HotelDireccion', 'HotelPoblacion', 'HotelZip', 'HotelProvinciaId', 'HotelNacionId', 'HotelTelefono', 'HotelFax', 'HotelCtaManocorriente', 'HotelDptoContable', 'HotelCtaContableCajas', 'HotelCtaContableBanco', 'HotelFechaInicioPrograma', 'HotelRutaFicheroPolicia', 'HotelContadorFicheroPolicia', 'HotelIdentificadorFicheroPolicia', 'HotelEmailReservas', 'HotelEmailVentas', 'HotelEmailSmtp', 'HotelTextoCancelacion', 'HotelUsuarioIsta', 'HotelPasswordIsta', 'HotelUrlIsta', 'HotelMunicipioIsta', 'HotelNumeroRegistroIsta', 'HotelRutaBavel', 'HotelDingusUsuario', 'HotelDingusPassword', 'HotelDingusHotelCode', 'HotelDingusTraductor', 'HotelDingusUrl', 'HotelCheckinOnLine', 'HotelMinimoDiasCheckinOnline', 'HotelZoomMapa', 'HotelLat', 'HotelLng', 'HotelAncho', 'HotelAlto', 'HotelOverbookingLimit', 'TipoHabitacionDescCorta', 'TipoHabitacionDescripcion', 'TipoHabitacionGrupoHabitacionId', 'TipoHabitacionNumeroPersonas', 'TipoHabitacionDesvios', 'TipoHabitacionNoShow', 'Situacion', 'ZonaLimpiezaHotelId', 'ZonaLimpiezaNombreZona'].forEach(x => (<any>Fields)[x] = x);
    }
}

